version: "3.9"

services:
  web:
    image: schedule-calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - webnet
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  webnet:
